apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-frontend
  namespace: ns-hiorder
  labels:
    app: hi-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hi-frontend
  template:
    metadata:
      labels:
        app: hi-frontend
        version: v1
    spec:
      containers:
      - name: hi-frontend
        image: ${ACR_LOGIN_SERVER}/hi-frontend:${IMAGE_TAG}
        ports:
        - containerPort: 80
          name: http
        env:
        - name: INGRESS_HOST
          value: "20.249.191.180"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        # securityContext 제거 (root로 실행하여 권한 문제 해결)
---
apiVersion: v1
kind: Service
metadata:
  name: hi-frontend-service
  namespace: ns-hiorder
  labels:
    app: hi-frontend
spec:
  selector:
    app: hi-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hi-frontend-ingress
  namespace: ns-hiorder
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hi-frontend-service
            port:
              number: 80